//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Web06.RESTful.Domain.Resource.Employee {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmployeeUS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmployeeUS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Web06.RESTful.Domain.Resource.Employee.EmployeeUS", typeof(EmployeeUS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        internal static string Excel_Column1 {
            get {
                return ResourceManager.GetString("Excel.Column1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee code.
        /// </summary>
        internal static string Excel_Column2 {
            get {
                return ResourceManager.GetString("Excel.Column2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee name.
        /// </summary>
        internal static string Excel_Column3 {
            get {
                return ResourceManager.GetString("Excel.Column3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Excel_Column4 {
            get {
                return ResourceManager.GetString("Excel.Column4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string Excel_Column5 {
            get {
                return ResourceManager.GetString("Excel.Column5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position name.
        /// </summary>
        internal static string Excel_Column6 {
            get {
                return ResourceManager.GetString("Excel.Column6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department name.
        /// </summary>
        internal static string Excel_Column7 {
            get {
                return ResourceManager.GetString("Excel.Column7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank account.
        /// </summary>
        internal static string Excel_Column8 {
            get {
                return ResourceManager.GetString("Excel.Column8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank name.
        /// </summary>
        internal static string Excel_Column9 {
            get {
                return ResourceManager.GetString("Excel.Column9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List_employee.xlsx.
        /// </summary>
        internal static string Excel_NameFile {
            get {
                return ResourceManager.GetString("Excel.NameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMPLOYEE LIST.
        /// </summary>
        internal static string Excel_NameSheet {
            get {
                return ResourceManager.GetString("Excel.NameSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMPLOYEE LIST.
        /// </summary>
        internal static string Excel_Title {
            get {
                return ResourceManager.GetString("Excel.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender.Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender.Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Gender_Other {
            get {
                return ResourceManager.GetString("Gender.Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
    }
}
